### PR TITLE
Switch to external zlib minizip library

### PR DESCRIPTION
**Pull request by winterheart**
Bundled unzip.[ch] uses deprecated zlib macros and fails to compile. Additionaly added pkg-config calls to use system libraries and includes.

### CODE REVIEW

**Comment by WickedSmoke** [comment]
The project is also built for Windows & Android, so I'd like to avoid adding a new external dependency.  What do you think of just updating the unzip.* code (and moving it to the support directory)?

I'd also like to minimize the number of build tools required, so unless the external libs are not found on your system I would forgo pkg-config.

**Comment by WickedSmoke** [comment]
More recent versions of the original [minizip](https://github.com/madler/zlib/tree/master/contrib/minizip) are no longer contained in a single file.

What are the errors being reported on your system?

**Comment by winterheart** [comment]
I got these errors:

```
$ ./configure 
Generating make.config & project.config
Now type make (or copr) to build.
$ make
make -C src -f Makefile xu4
make[1]: Entering directory '/home/winterheart/playground/u4/src'
cc -Wall -I. -Isupport -DUSE_BORON -DCONF_MODULE -DVERSION=\"DR-1.0\" -O3 -DNDEBUG -Iglv/x11 -DUSE_CURSORS   -c -o unzip.o unzip.c
In file included from unzip.c:15:
unzip.h:114:45: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  114 | extern int ZEXPORT unzStringFileNameCompare OF ((const char* fileName1,
      |                                             ^~
unzip.h:127:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  127 | extern unzFile ZEXPORT unzOpen OF((const char *path));
      |                                ^~
unzip.h:138:29: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  138 | extern int ZEXPORT unzClose OF((unzFile file));
      |                             ^~
unzip.h:145:37: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  145 | extern int ZEXPORT unzGetGlobalInfo OF((unzFile file,
      |                                     ^~
unzip.h:153:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  153 | extern int ZEXPORT unzGetGlobalComment OF((unzFile file,
      |                                        ^~
unzip.h:166:37: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  166 | extern int ZEXPORT unzGoToFirstFile OF((unzFile file));
      |                                     ^~
unzip.h:172:36: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  172 | extern int ZEXPORT unzGoToNextFile OF((unzFile file));
      |                                    ^~
unzip.h:179:34: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  179 | extern int ZEXPORT unzLocateFile OF((unzFile file,
      |                                  ^~
unzip.h:192:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  192 | extern int ZEXPORT unzGetCurrentFileInfo OF((unzFile file,
      |                                          ^~
unzip.h:218:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  218 | extern int ZEXPORT unzOpenCurrentFile OF((unzFile file));
      |                                       ^~
unzip.h:224:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  224 | extern int ZEXPORT unzCloseCurrentFile OF((unzFile file));
      |                                        ^~
unzip.h:231:39: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  231 | extern int ZEXPORT unzReadCurrentFile OF((unzFile file,
      |                                       ^~
unzip.h:245:32: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  245 | extern z_off_t ZEXPORT unztell OF((unzFile file));
      |                                ^~
unzip.h:250:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  250 | extern int ZEXPORT unzeof OF((unzFile file));
      |                           ^~
unzip.h:255:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  255 | extern int ZEXPORT unzGetLocalExtrafield OF((unzFile file,
      |                                          ^~
unzip.c: In function 'unzOpen':
unzip.c:421:5: warning: implicit declaration of function 'unzGoToFirstFile' [-Wimplicit-function-declaration]
  421 |     unzGoToFirstFile((unzFile)s);
      |     ^~~~~~~~~~~~~~~~
unzip.c: In function 'unzClose':
unzip.c:439:9: warning: implicit declaration of function 'unzCloseCurrentFile' [-Wimplicit-function-declaration]
  439 |         unzCloseCurrentFile(file);
      |         ^~~~~~~~~~~~~~~~~~~
unzip.c: At top level:
unzip.c:481:47: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  481 | local int unzlocal_GetCurrentFileInfoInternal OF((unzFile file,
      |                                               ^~
make[1]: *** [<builtin>: unzip.o] Error 1
make[1]: Leaving directory '/home/winterheart/playground/u4/src'
make: *** [Makefile:20: src/xu4] Error 2
```
OS Gentoo Linux
GCC 12
zlib 1.2.13

`OF` macros is zlib related ones which was renamed to Z_OF in 1.1 or 1.2 (?) version of zlib. I've tried to update zip.h and zip.c from recent zlib version but got another error, so I decided to switch system minizip.

**Comment by WickedSmoke** [comment]
The official sources from zlib.net still uses the "OF" macro in 1.2.13.  What source is Gentoo using that renames it?

**Comment by winterheart** [comment]
Indeed, this is Gentoo specific things: https://bugs.gentoo.org/383179. While this OS specific issue, can be it fixed by providing option to user to decide which unzip should be used - built-in or system?

**Comment by WickedSmoke** [comment]
Adding a new build option will touch a few files and requires action by developers.   Here's my proposal for a minimal fix: https://github.com/xu4-engine/u4/commit/290c00971

If that's acceptable to you please let me know if it works on your system.

**Comment by WickedSmoke** [comment]
The Makefile.common change breaks other platforms so this patch cannot be accepted.

The unzip.h header change has been pushed to master in commit 75b57209 so the build should work OK for Gentoo users now.

**Pull request closed without merging**
