### PR TITLE
Make setup script portable to other Linux distros

### PR DESCRIPTION
**Pull request by chocorho**
When I originally went to run the setup-script that was included in the "Beta 5" release, I encountered an error due to the hashbang (in full disclosure, I am on a Devuan Chimaera system). I have adjusted this so that the script is more portable, on my machine and on others.

Any feedback is welcome.

### CODE REVIEW

**Comment by WickedSmoke** [comment]
I see /bin/sh is recommended by some.  What is the exact path to sh on your distro?

Other than that, does the script work?  What is latest Allegro version provided by Debian?

**Comment by chocorho** [comment]
I can confirm that `/bin/sh` exists, though it turns out to be a symbolic link to `/bin/dash` on my machine (I never realized this, haha).

And uhh, hmm, good point. Now, the script simply outputs "You will need to install Allegro 5 manually."

The truth is, I am accustomed to building Allegro 5 from scratch, so this doesn't bother me, but for the sake of the PR, I should probably add a case for Debian, right?

I'll add it in a moment...

**Comment by chocorho** [comment]
Here's the link to the debian package; I believe it selects `5.2.6` by default, unless you enable testing repositories, which use `5.2.7`.

**Comment by chocorho** [comment]
> Here's the link to the debian package; I believe it selects `5.2.6` by default, unless you enable testing repositories, which use `5.2.7`.

https://tracker.debian.org/pkg/allegro5

**Comment by WickedSmoke** [comment]
If you would change the Debian case to install the acodec package rather than -dev and indent with tabs I will squash and pull this.

If the Ubuntu PPA was dropped (using the outdated Allegro) debian & ubuntu could probably be merged.  The Pulse Audio bug in earlier versions is pretty bad though...

**Comment by WickedSmoke** [comment]
Oh, and I'm going to update dist/README.linux-dr in the commit as well

**Comment by chocorho** [comment]
Ah, you're right, the ubuntu case now looks awfully similar to the debian case... normally I'd recommend using a "fall-through" mechanic, but I get the impression that the `;&` is [only supported by some shell versions and not others](https://stackoverflow.com/a/12010977).

I'm not sure how important the PPA is for istallation on Ubuntu, but I'm pretty sure it won't work on debian, so we cannot simply merge the two cases. We might just have to bite the bullet and keep them as two separate (similar-looking) cases.

**Comment by WickedSmoke** [comment]
Pulled as commit c98ece8504.

**Pull request closed without merging**
